// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg8rbNH3wJk8N0C7dX1ZhLBm3erQ1rjjI',
    appId: '1:204323641418:web:3e9c63ba678bd0a78deeb3',
    messagingSenderId: '204323641418',
    projectId: 'biometriclogin-55da8',
    authDomain: 'biometriclogin-55da8.firebaseapp.com',
    storageBucket: 'biometriclogin-55da8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpaMzNohOk5yrevZ-YhUNGeHdeSAXkgUU',
    appId: '1:204323641418:android:19f87ebd494239ef8deeb3',
    messagingSenderId: '204323641418',
    projectId: 'biometriclogin-55da8',
    storageBucket: 'biometriclogin-55da8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN6657IwK1QS6txu4UwOf99xXFjRkQ-Zw',
    appId: '1:204323641418:ios:3513055c10d6fa368deeb3',
    messagingSenderId: '204323641418',
    projectId: 'biometriclogin-55da8',
    storageBucket: 'biometriclogin-55da8.appspot.com',
    iosBundleId: 'com.example.biometriclogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN6657IwK1QS6txu4UwOf99xXFjRkQ-Zw',
    appId: '1:204323641418:ios:0bbdbff1270b14fc8deeb3',
    messagingSenderId: '204323641418',
    projectId: 'biometriclogin-55da8',
    storageBucket: 'biometriclogin-55da8.appspot.com',
    iosBundleId: 'com.example.biometriclogin.RunnerTests',
  );
}
